# Generated by Django 2.2.6 on 2019-11-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20191115_0238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
