# Generated by Django 2.2.6 on 2019-12-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='fio',
        ),
        migrations.AddField(
            model_name='basket',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
