# Generated by Django 2.2.6 on 2019-12-25 00:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_auto_20191221_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='address',
            field=models.CharField(default='', max_length=128, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='delivery_date',
            field=models.DateTimeField(null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='email',
            field=models.EmailField(default='', max_length=255, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='info',
            field=models.TextField(default='', max_length=512, verbose_name='Заметки модераторов'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='phone_number',
            field=models.CharField(default='', max_length=16, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Заказ оплачен'), (1, 'Товар отправлен'), (2, 'Товар доставлен')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='sum_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Суммарная цена'),
        ),
        migrations.AlterField(
            model_name='category',
            name='discount',
            field=models.FloatField(default=0.0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='lore',
            field=models.TextField(default='', max_length=3000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=28, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=3000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0.0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выставки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0, verbose_name='Продано'),
        ),
        migrations.AlterField(
            model_name='singleorder',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='singleorder',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Basket', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='singleorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='singleorder',
            name='sum_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Суммарная цена'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=64, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=64, unique=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Подтвердил почту'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=33, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=16, verbose_name='Телефон'),
        ),
        migrations.DeleteModel(
            name='PersonalDiscount',
        ),
    ]
