# Generated by Django 2.2.6 on 2019-12-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_auto_20191225_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
